### ISSUE TITLE
Support structured concurrency

### ISSUE THREAD

**Issue by sormuras** [sormuras/bach#179]
Similar to https://github.com/sormuras/bach/commit/d88cca1e8d272aacc09b1cb763e113011b417eeb

**Comment by jbduncan** [comment]
@sormuras Having read the commit linked in your opening comment, it occurs to me that using `.parallel()` streams to parallelize IO operations as you do there is [not](https://github.com/google/mug/wiki/Parallelizer-Explained) really [ideal](https://github.com/code-review-checklists/java-concurrency#fjp-no-blocking).

That said, I'm not clear what your intention with this issue is (I see the title used to refer to Bach's `ToolRunner`), and it occurs to me that this issue's name refers to structured concurrency, which I personally associate with Golang's goroutines and Project Loom's lightweight threads.

Am I right to infer that you want to use Loom or even the pre-Loom examples in your [blog post](https://sormuras.github.io/blog/2020-06-16-structured-concurrency-today) instead of `.parallel()`? If so, this sounds like an good idea to me!

**Comment by sormuras** [comment]
Hi Jonathan,

thanks for your feedback. In the long-run, I do intend to make use of virtual threads here. For the time being, I'm fine with Bach running tools in a single thread -- there're still some open ends (find and fix bugs, implement nice-to-have features, and document the whole thing) to resolve, first. That's why I moved this issue to target milestone 17.

**Comment by jbduncan** [comment]
Fair enough! Cheers for the quick response. 👍 

Although I'm actually not clear what you meant by "single-threaded" just now. I was under the impression that the current code in that file does things on multiple threads now, just using `.stream().parallel()` for everything, including IO-bound operations for which parallel streams are not ideal. Have I misunderstood something here?

**Comment by sormuras** [comment]
The code I refered to belongs to an already deprecated version of Bach, namely `11`. With Bach `16` everything's plain and simple for the time being:

https://github.com/sormuras/bach/blob/f754afaf08aab75b2e5d6d5ee2a58dc9b6ce5f9f/com.github.sormuras.bach/main/java/com/github/sormuras/bach/Builder.java#L478-L488

Some day in 2021, there'll be another `run` method taking an array of tool calls, which returns when all passed calls were executed.

**Comment by jbduncan** [comment]
Ooh, I see! I should've checked the current version of that file in hindsight. Many thanks for clearing things up.
