### ISSUE TITLE
Tests are not executed

### ISSUE THREAD

**Issue by khmarbaise** [sormuras/bach#213]
https://github.com/khmarbaise/kata-fraction/tree/bach

Currently I can build on plain command line without issue but it looks like I've overlooked something related to unit tests they are not executed. My assumption that I missed some kind of setup/configuration.

Unfortunately I haven't find something about related in the docs.

**Comment by sormuras** [comment]
It's due to a combination of (at least) two bugs in Bach and a non-matching glob pattern configured for test modules; plus missing "external module lookup directives", which I didn't document, yet.

Fixes are in progress...
- Bach's "test code space builder"
- https://github.com/khmarbaise/kata-fraction/compare/bach...sormuras:bach

**Comment by sormuras** [comment]
https://github.com/sormuras/bach/blob/b798489ac16c601b53d804ef3f41f8a05ea47de1/com.github.sormuras.bach/main/java/com/github/sormuras/bach/project/Spaces.java#L8

This line (read: the composed module finder) hides test modules and their `requires` directives -- which in turns hides them from computation of missing external modules. Using both (main and test) declarations components individually should fix this.
